### ISSUE TITLE
default hipster app run with error

### ISSUE THREAD

**Issue by shougao** [mshima/generator-jhipster-multitenancy2#1] opened 2019-07-23 12:07 UTC
first, this is a grate project for JHipster, and it save more time to me.
thank you very much for your grate work.

I meet 2 error, please help.

using JHipster 6.1.2 and this blueprint to get the monolithic application, successful.

then run ./mvnw and get the error.

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jhipster ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 76 source files to /Users/eric/Development/jhipster/my-tenancy/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/eric/Development/jhipster/my-tenancy/src/main/java/com/mycompany/tenancytest/web/rest/CompanyResource.java:[64,76] illegal start of expression
[ERROR] /Users/eric/Development/jhipster/my-tenancy/src/main/java/com/mycompany/tenancytest/web/rest/CompanyResource.java:[85,74] illegal start of expression
[ERROR] /Users/eric/Development/jhipster/my-tenancy/src/main/java/com/mycompany/tenancytest/web/rest/CompanyResource.java:[132,105] illegal start of expression
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

check the code, only 3 parameters ,the function need 4parameters.

when I change the 2nd parameter to true, I got the new error.
       HeaderUtil.createEntityDeletionAlert(applicationName,  , ENTITY_NAME, id.toString())).build();
       HeaderUtil.createEntityDeletionAlert(applicationName, true, ENTITY_NAME, id.toString())).build();

[WARNING] npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
[ERROR] 
[ERROR] npm ERR! path /Users/eric/Development/jhipster/generator-jhipster-multitenancy2/node_modules/async
[ERROR] npm ERR! code EACCES
[ERROR] npm ERR! errno -13
[ERROR] npm ERR! syscall access
[ERROR] npm ERR! Error: EACCES: permission denied, access '/Users/eric/Development/jhipster/generator-jhipster-multitenancy2/node_modules/async'
[ERROR] npm ERR!  { [Error: EACCES: permission denied, access '/Users/eric/Development/jhipster/generator-jhipster-multitenancy2/node_modules/async']
[ERROR] npm ERR!   stack:
[ERROR] npm ERR!    'Error: EACCES: permission denied, access \'/Users/eric/Development/jhipster/generator-jhipster-multitenancy2/node_modules/async\'',
[ERROR] npm ERR!   errno: -13,
[ERROR] npm ERR!   code: 'EACCES',
[ERROR] npm ERR!   syscall: 'access',
[ERROR] npm ERR!   path:
[ERROR] npm ERR!    '/Users/eric/Development/jhipster/generator-jhipster-multitenancy2/node_modules/async' }
[ERROR] npm ERR! 
[ERROR] npm ERR! The operation was rejected by your operating system.
[ERROR] npm ERR! It is likely you do not have the permissions to access this file as the current user
[ERROR] npm ERR! 
[ERROR] npm ERR! If you believe this might be a permissions issue, please double-check the
[ERROR] npm ERR! permissions of the file and its containing directories, or try running
[ERROR] npm ERR! the command again as root/Administrator (though this is not recommended).
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /Users/eric/.npm/_logs/2019-07-23T13_16_04_292Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:48 min
[INFO] Finished at: 2019-07-23T21:16:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm install) on project jhipster: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 243 (Exit value: 243) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
ericmac:my-tenancy eric$ 

please help to update.

**Comment by mshima** [comment] 2019-07-24 17:15
Weird, cannot reproduce.

The change made to TenantResource.java is minor:

https://github.com/mshima/generator-jhipster-multitenancy2/blob/master/generators/entity-server/partials/server/_TenantResource.js

**Comment by mshima** [comment] 2019-07-25 20:02
Closing the issue, need more info.

**Closed** 2019-07-25 20:03 UTC
